// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import ()

type Event struct {
	ID                int64
	Title             string
	Date              string
	IsNationalHoliday bool
}
